/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    'product-tags': ProductTag;
    products: Product;
    'product-attributes': ProductAttribute;
    'product-images': ProductImage;
    orders: Order;
    coupons: Coupon;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'product-tags': ProductTagsSelect<false> | ProductTagsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'product-attributes': ProductAttributesSelect<false> | ProductAttributesSelect<true>;
    'product-images': ProductImagesSelect<false> | ProductImagesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    coupons: CouponsSelect<false> | CouponsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'commerce-settings': CommerceSetting;
    'home-content': HomeContent;
    'pdp-content': PdpContent;
    'site-settings': SiteSetting;
    'ayuda-content': AyudaContent;
    navigation: Navigation;
  };
  globalsSelect: {
    'commerce-settings': CommerceSettingsSelect<false> | CommerceSettingsSelect<true>;
    'home-content': HomeContentSelect<false> | HomeContentSelect<true>;
    'pdp-content': PdpContentSelect<false> | PdpContentSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'ayuda-content': AyudaContentSelect<false> | AyudaContentSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Gestión de clientes y usuarios internos. Los clientes se registran desde el storefront. Solo admin puede eliminar registros para preservar historial de pedidos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'visitor' | 'retail' | 'wholesale' | 'staff' | 'admin';
  customer_type: 'RETAIL' | 'WHOLESALE';
  name: string;
  phone?: string | null;
  /**
   * Teléfono alternativo opcional del cliente (Mi cuenta).
   */
  phoneAlt?: string | null;
  business_name?: string | null;
  cuit?: string | null;
  province?: string | null;
  city?: string | null;
  whatsapp?: string | null;
  /**
   * Dirección principal de entrega (Mi cuenta). Se usa por defecto para futuros envíos.
   */
  address?: {
    street?: string | null;
    number?: string | null;
    apartment?: string | null;
    postalCode?: string | null;
    locality?: string | null;
    province?: string | null;
    references?: string | null;
  };
  /**
   * Direcciones adicionales de entrega (Mi cuenta).
   */
  addresses?:
    | {
        label: string;
        street?: string | null;
        number?: string | null;
        apartment?: string | null;
        postalCode?: string | null;
        locality?: string | null;
        province?: string | null;
        references?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    desktop?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Jerarquía de categorías del catálogo. Soporta sub-categorías vía campo parent y orden manual vía sortOrder.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  image?: (number | null) | Media;
  parent?: (number | null) | Category;
  sortOrder?: number | null;
  featured?: boolean | null;
  active?: boolean | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-tags".
 */
export interface ProductTag {
  id: number;
  name: string;
  slug: string;
  /**
   * Aroma y Ritual aparecen como opciones de filtro en el catálogo; General solo como Tipo.
   */
  kind: 'aroma' | 'ritual' | 'general';
  description?: string | null;
  color?: string | null;
  icon?: string | null;
  sortOrder?: number | null;
  featured?: boolean | null;
  active?: boolean | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Catálogo único de productos REGALARTE. No existen catálogos paralelos para mayoristas: el flag isWholesaleAvailable define qué productos aplican precio B2B.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  price: number;
  compareAtPrice?: number | null;
  /**
   * Si está vacío y el producto mayorista, no aplica precio B2B.
   */
  wholesalePrice?: number | null;
  isWholesaleAvailable?: boolean | null;
  sku?: string | null;
  stock?: number | null;
  active?: boolean | null;
  featured?: boolean | null;
  /**
   * Marca el producto como parte del universo Solística. No es un catálogo paralelo: sigue siendo un producto REGALARTE.
   */
  isSolistica?: boolean | null;
  sortOrder?: number | null;
  category: number | Category;
  /**
   * El producto sigue visible en catálogo y PDP pero no se puede comprar.
   */
  soldOut?: boolean | null;
  tags?: (number | ProductTag)[] | null;
  attributes?: (number | ProductAttribute)[] | null;
  images?: (number | ProductImage)[] | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-attributes".
 */
export interface ProductAttribute {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  values: {
    value: string;
    sortOrder?: number | null;
    id?: string | null;
  }[];
  sortOrder?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-images".
 */
export interface ProductImage {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    desktop?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Pedidos generados por el checkout. El admin puede ver y actualizar el estado (p. ej. pending → paid). El storefront solo crea orders via POST /api/orders; nunca las lee.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * Identificador público human-readable (ej. RG-2026-00001).
   */
  orderNumber: string;
  status: 'pending' | 'paid' | 'rejected' | 'cancelled' | 'fulfilled';
  mode: 'RETAIL' | 'WHOLESALE';
  customer: {
    firstName: string;
    lastName: string;
    email: string;
    phone: string;
  };
  address: {
    province: string;
    city: string;
    street: string;
    postalCode: string;
  };
  notes?: {
    message?: string | null;
  };
  items: {
    product: number | Product;
    slug: string;
    name: string;
    quantity: number;
    unitPrice: number;
    lineTotal: number;
    id?: string | null;
  }[];
  subtotal: number;
  shipping: number;
  couponCode?: string | null;
  discount: number;
  total: number;
  /**
   * Completado por el provider tras la inicialización del pago.
   */
  paymentProvider?: ('mock' | 'mercadopago') | null;
  /**
   * Identificador devuelto por el provider (preference_id, etc.).
   */
  paymentExternalId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Cupones de descuento porcentual aplicables en el checkout. Solo admin.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons".
 */
export interface Coupon {
  id: number;
  /**
   * Se guarda en mayúsculas y sin espacios.
   */
  code: string;
  /**
   * Porcentaje sobre el subtotal del pedido (1 a 100).
   */
  percent: number;
  /**
   * Un cupón inactivo se rechaza en el checkout.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'product-tags';
        value: number | ProductTag;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'product-attributes';
        value: number | ProductAttribute;
      } | null)
    | ({
        relationTo: 'product-images';
        value: number | ProductImage;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'coupons';
        value: number | Coupon;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  customer_type?: T;
  name?: T;
  phone?: T;
  phoneAlt?: T;
  business_name?: T;
  cuit?: T;
  province?: T;
  city?: T;
  whatsapp?: T;
  address?:
    | T
    | {
        street?: T;
        number?: T;
        apartment?: T;
        postalCode?: T;
        locality?: T;
        province?: T;
        references?: T;
      };
  addresses?:
    | T
    | {
        label?: T;
        street?: T;
        number?: T;
        apartment?: T;
        postalCode?: T;
        locality?: T;
        province?: T;
        references?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        desktop?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  image?: T;
  parent?: T;
  sortOrder?: T;
  featured?: T;
  active?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-tags_select".
 */
export interface ProductTagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  kind?: T;
  description?: T;
  color?: T;
  icon?: T;
  sortOrder?: T;
  featured?: T;
  active?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  price?: T;
  compareAtPrice?: T;
  wholesalePrice?: T;
  isWholesaleAvailable?: T;
  sku?: T;
  stock?: T;
  active?: T;
  featured?: T;
  isSolistica?: T;
  sortOrder?: T;
  category?: T;
  soldOut?: T;
  tags?: T;
  attributes?: T;
  images?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-attributes_select".
 */
export interface ProductAttributesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  values?:
    | T
    | {
        value?: T;
        sortOrder?: T;
        id?: T;
      };
  sortOrder?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-images_select".
 */
export interface ProductImagesSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        desktop?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  status?: T;
  mode?: T;
  customer?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        email?: T;
        phone?: T;
      };
  address?:
    | T
    | {
        province?: T;
        city?: T;
        street?: T;
        postalCode?: T;
      };
  notes?:
    | T
    | {
        message?: T;
      };
  items?:
    | T
    | {
        product?: T;
        slug?: T;
        name?: T;
        quantity?: T;
        unitPrice?: T;
        lineTotal?: T;
        id?: T;
      };
  subtotal?: T;
  shipping?: T;
  couponCode?: T;
  discount?: T;
  total?: T;
  paymentProvider?: T;
  paymentExternalId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons_select".
 */
export interface CouponsSelect<T extends boolean = true> {
  code?: T;
  percent?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Parámetros administrativos de la tienda. Modificables únicamente por admin y staff.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commerce-settings".
 */
export interface CommerceSetting {
  id: number;
  /**
   * Habilita el canal mayorista en la storefront. Cuando está deshabilitado, los mayoristas no pueden comprar.
   */
  wholesale_enabled: boolean;
  /**
   * Monto (en ARS) del subtotal desde el cual el carrito muestra el envío gratis. Alimenta la barra de progreso del carrito.
   */
  free_shipping_threshold: number;
  /**
   * Monto mínimo (en ARS) que debe alcanzar un pedido para ser aceptado en el canal mayorista.
   */
  minimum_wholesale_order: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Textos e imágenes comerciales de la Home (Modo Edición Guale). Modificable únicamente por admin y staff.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-content".
 */
export interface HomeContent {
  id: number;
  /**
   * Imagen, título, descripción y texto del botón de cada slide.
   */
  heroSlides?:
    | {
        image: string;
        title: string;
        description?: string | null;
        /**
         * Vacío = texto derivado de la categoría ("EXPLORAR ...").
         */
        ctaText?: string | null;
        category: 'velas' | 'aromas' | 'wax-melts' | 'quemadores' | 'packs' | 'regalarte';
        id?: string | null;
      }[]
    | null;
  intro?: {
    title?: string | null;
    description?: string | null;
  };
  /**
   * Títulos y textos de la tira de beneficios de la Home.
   */
  benefits?:
    | {
        icon: 'shipping' | 'packaging' | 'payment' | 'leaf' | 'support';
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Título y texto comercial de cada sección de la Home.
   */
  sections?:
    | {
        categorySlug: 'velas' | 'aromas' | 'wax-melts' | 'quemadores' | 'packs' | 'regalarte';
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Textos editoriales de las pestañas del PDP (Modo Edición Guale). Modificable únicamente por admin y staff.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pdp-content".
 */
export interface PdpContent {
  id: number;
  comoUsar?: string | null;
  detalles?: string | null;
  gifting?: string | null;
  faq?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Enlaces de redes sociales y de contacto (pie de página y página de Ayuda). Vacío = valor por defecto.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  instagramUrl?: string | null;
  tiktokUrl?: string | null;
  facebookUrl?: string | null;
  /**
   * Enlace de contacto de la sección Contacto de Ayuda (ej: https://wa.me/549...).
   */
  whatsappUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Secciones de la página de Ayuda. Sin secciones guardadas se usa el contenido por defecto.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ayuda-content".
 */
export interface AyudaContent {
  id: number;
  sections?:
    | {
        /**
         * Minúsculas, números y guiones. Se usa en /ayuda#identificador.
         */
        sectionId: string;
        title: string;
        intro?: string | null;
        body?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        ctaLabel?: string | null;
        /**
         * Ruta interna, ej: /catalogo
         */
        ctaHref?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Opciones del menú principal. También se editan desde la tienda con "Editar navegación". Sin opciones guardadas se usa el menú por defecto.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  items?:
    | {
        label: string;
        destinationType: 'category' | 'path';
        category?: (number | null) | Category;
        path?: string | null;
        active?: boolean | null;
        accent?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commerce-settings_select".
 */
export interface CommerceSettingsSelect<T extends boolean = true> {
  wholesale_enabled?: T;
  free_shipping_threshold?: T;
  minimum_wholesale_order?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-content_select".
 */
export interface HomeContentSelect<T extends boolean = true> {
  heroSlides?:
    | T
    | {
        image?: T;
        title?: T;
        description?: T;
        ctaText?: T;
        category?: T;
        id?: T;
      };
  intro?:
    | T
    | {
        title?: T;
        description?: T;
      };
  benefits?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        categorySlug?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pdp-content_select".
 */
export interface PdpContentSelect<T extends boolean = true> {
  comoUsar?: T;
  detalles?: T;
  gifting?: T;
  faq?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  instagramUrl?: T;
  tiktokUrl?: T;
  facebookUrl?: T;
  whatsappUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ayuda-content_select".
 */
export interface AyudaContentSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        sectionId?: T;
        title?: T;
        intro?: T;
        body?:
          | T
          | {
              text?: T;
              id?: T;
            };
        ctaLabel?: T;
        ctaHref?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        destinationType?: T;
        category?: T;
        path?: T;
        active?: T;
        accent?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}